<?php

namespace ContainerMbYnDSy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TROA66pService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TROA66p' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TROA66p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'clientRepository' => ['privates', 'App\\Repository\\ClientRepository', 'getClientRepositoryService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', true],
        ], [
            'clientRepository' => 'App\\Repository\\ClientRepository',
            'serializer' => '?',
        ]);
    }
}
