<?php

namespace ContainerMbYnDSy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N3JqhkLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.N3JqhkL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.N3JqhkL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'client' => ['privates', '.errored..service_locator.N3JqhkL.App\\Entity\\Client', NULL, 'Cannot autowire service ".service_locator.N3JqhkL": it needs an instance of "App\\Entity\\Client" but this type has been excluded in "config/services.yaml".'],
            'serializer' => ['privates', 'serializer', 'getSerializerService', true],
        ], [
            'client' => 'App\\Entity\\Client',
            'serializer' => '?',
        ]);
    }
}
