<?php

namespace ContainerMbYnDSy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4ldWA5vService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4ldWA5v' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4ldWA5v'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mobile' => ['privates', '.errored..service_locator.4ldWA5v.App\\Entity\\Mobile', NULL, 'Cannot autowire service ".service_locator.4ldWA5v": it needs an instance of "App\\Entity\\Mobile" but this type has been excluded in "config/services.yaml".'],
            'serializer' => ['services', 'jms_serializer', 'getJmsSerializerService', true],
        ], [
            'mobile' => 'App\\Entity\\Mobile',
            'serializer' => '?',
        ]);
    }
}
