<?php

namespace ContainerTelvUQh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OGNHoCOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oGNHoCO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oGNHoCO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cache' => ['privates', 'cache.app.taggable', 'getCache_App_TaggableService', true],
            'serializer' => ['services', 'jms_serializer', 'getJmsSerializerService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'cache' => '?',
            'serializer' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
