<?php

namespace ContainerTelvUQh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LCQc_YService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.l_CQc.y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.l_CQc.y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'brandRepository' => ['privates', 'App\\Repository\\BrandRepository', 'getBrandRepositoryService', true],
            'cache' => ['privates', 'cache.app.taggable', 'getCache_App_TaggableService', true],
            'currentMobile' => ['privates', '.errored..service_locator.l_CQc.y.App\\Entity\\Mobile', NULL, 'Cannot autowire service ".service_locator.l_CQc.y": it needs an instance of "App\\Entity\\Mobile" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'serializer' => ['services', 'jms_serializer', 'getJmsSerializerService', true],
            'validator' => ['privates', 'validator', 'getValidatorService', true],
        ], [
            'brandRepository' => 'App\\Repository\\BrandRepository',
            'cache' => '?',
            'currentMobile' => 'App\\Entity\\Mobile',
            'em' => '?',
            'serializer' => '?',
            'validator' => '?',
        ]);
    }
}
