<?php

namespace ContainerTelvUQh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUser2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.GkGK2OS.App\Entity\User' shared service.
     *
     * @return \App\Entity\User
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.GkGK2OS": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".');
    }
}
