<?php

namespace Container6Ol5PwU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GYw5OWQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GYw5OWQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GYw5OWQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'mobile' => ['privates', '.errored..service_locator.GYw5OWQ.App\\Entity\\Mobile', NULL, 'Cannot autowire service ".service_locator.GYw5OWQ": it needs an instance of "App\\Entity\\Mobile" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'mobile' => 'App\\Entity\\Mobile',
        ]);
    }
}
