<?php

namespace ContainerHxLeubD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ekshx4rService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ekshx4r' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ekshx4r'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cache' => ['privates', 'cache.app.taggable', 'getCache_App_TaggableService', true],
            'mobileRepository' => ['privates', 'App\\Repository\\MobileRepository', 'getMobileRepositoryService', true],
            'serializer' => ['services', 'jms_serializer', 'getJmsSerializerService', true],
        ], [
            'cache' => '?',
            'mobileRepository' => 'App\\Repository\\MobileRepository',
            'serializer' => '?',
        ]);
    }
}
