<?php

namespace ContainerKZMbxY0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SneMxG2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SneMxG2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SneMxG2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BrandController::createBrand' => ['privates', '.service_locator.U1eLwaY', 'get_ServiceLocator_U1eLwaYService', true],
            'App\\Controller\\BrandController::deleteBrand' => ['privates', '.service_locator.riyQT5B', 'get_ServiceLocator_RiyQT5BService', true],
            'App\\Controller\\BrandController::getBrandList' => ['privates', '.service_locator.h95eEDj', 'get_ServiceLocator_H95eEDjService', true],
            'App\\Controller\\BrandController::getDetailBrand' => ['privates', '.service_locator.Y58uPq8', 'get_ServiceLocator_Y58uPq8Service', true],
            'App\\Controller\\BrandController::updateBrand' => ['privates', '.service_locator.dfP61RH', 'get_ServiceLocator_DfP61RHService', true],
            'App\\Controller\\MobileController::createMobile' => ['privates', '.service_locator.K3s_sj8', 'get_ServiceLocator_K3sSj8Service', true],
            'App\\Controller\\MobileController::deleteMobile' => ['privates', '.service_locator.SZvQUVg', 'get_ServiceLocator_SZvQUVgService', true],
            'App\\Controller\\MobileController::getAllMobiles' => ['privates', '.service_locator.Ekshx4r', 'get_ServiceLocator_Ekshx4rService', true],
            'App\\Controller\\MobileController::getDetailMobile' => ['privates', '.service_locator.q.Wxh1.', 'get_ServiceLocator_Q_Wxh1_Service', true],
            'App\\Controller\\MobileController::updateMobile' => ['privates', '.service_locator.l_CQc.y', 'get_ServiceLocator_LCQc_YService', true],
            'App\\Controller\\UserController::createClient' => ['privates', '.service_locator.BxJ7Dmm', 'get_ServiceLocator_BxJ7DmmService', true],
            'App\\Controller\\UserController::createUser' => ['privates', '.service_locator.BxJ7Dmm', 'get_ServiceLocator_BxJ7DmmService', true],
            'App\\Controller\\UserController::deleteClient' => ['privates', '.service_locator.GkGK2OS', 'get_ServiceLocator_GkGK2OSService', true],
            'App\\Controller\\UserController::deleteUser' => ['privates', '.service_locator.N7XwuMC', 'get_ServiceLocator_N7XwuMCService', true],
            'App\\Controller\\UserController::getClientList' => ['privates', '.service_locator.oGNHoCO', 'get_ServiceLocator_OGNHoCOService', true],
            'App\\Controller\\UserController::getDetailClient' => ['privates', '.service_locator.ErOnR4h', 'get_ServiceLocator_ErOnR4hService', true],
            'App\\Controller\\UserController::getDetailUser' => ['privates', '.service_locator.ErOnR4h', 'get_ServiceLocator_ErOnR4hService', true],
            'App\\Controller\\UserController::getUserList' => ['privates', '.service_locator.oGNHoCO', 'get_ServiceLocator_OGNHoCOService', true],
            'App\\Controller\\UserController::linkUser' => ['privates', '.service_locator.sbrKPjh', 'get_ServiceLocator_SbrKPjhService', true],
            'App\\Controller\\UserController::updateUser' => ['privates', '.service_locator.80_A3kY', 'get_ServiceLocator_80A3kYService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\BrandController:createBrand' => ['privates', '.service_locator.U1eLwaY', 'get_ServiceLocator_U1eLwaYService', true],
            'App\\Controller\\BrandController:deleteBrand' => ['privates', '.service_locator.riyQT5B', 'get_ServiceLocator_RiyQT5BService', true],
            'App\\Controller\\BrandController:getBrandList' => ['privates', '.service_locator.h95eEDj', 'get_ServiceLocator_H95eEDjService', true],
            'App\\Controller\\BrandController:getDetailBrand' => ['privates', '.service_locator.Y58uPq8', 'get_ServiceLocator_Y58uPq8Service', true],
            'App\\Controller\\BrandController:updateBrand' => ['privates', '.service_locator.dfP61RH', 'get_ServiceLocator_DfP61RHService', true],
            'App\\Controller\\MobileController:createMobile' => ['privates', '.service_locator.K3s_sj8', 'get_ServiceLocator_K3sSj8Service', true],
            'App\\Controller\\MobileController:deleteMobile' => ['privates', '.service_locator.SZvQUVg', 'get_ServiceLocator_SZvQUVgService', true],
            'App\\Controller\\MobileController:getAllMobiles' => ['privates', '.service_locator.Ekshx4r', 'get_ServiceLocator_Ekshx4rService', true],
            'App\\Controller\\MobileController:getDetailMobile' => ['privates', '.service_locator.q.Wxh1.', 'get_ServiceLocator_Q_Wxh1_Service', true],
            'App\\Controller\\MobileController:updateMobile' => ['privates', '.service_locator.l_CQc.y', 'get_ServiceLocator_LCQc_YService', true],
            'App\\Controller\\UserController:createClient' => ['privates', '.service_locator.BxJ7Dmm', 'get_ServiceLocator_BxJ7DmmService', true],
            'App\\Controller\\UserController:createUser' => ['privates', '.service_locator.BxJ7Dmm', 'get_ServiceLocator_BxJ7DmmService', true],
            'App\\Controller\\UserController:deleteClient' => ['privates', '.service_locator.GkGK2OS', 'get_ServiceLocator_GkGK2OSService', true],
            'App\\Controller\\UserController:deleteUser' => ['privates', '.service_locator.N7XwuMC', 'get_ServiceLocator_N7XwuMCService', true],
            'App\\Controller\\UserController:getClientList' => ['privates', '.service_locator.oGNHoCO', 'get_ServiceLocator_OGNHoCOService', true],
            'App\\Controller\\UserController:getDetailClient' => ['privates', '.service_locator.ErOnR4h', 'get_ServiceLocator_ErOnR4hService', true],
            'App\\Controller\\UserController:getDetailUser' => ['privates', '.service_locator.ErOnR4h', 'get_ServiceLocator_ErOnR4hService', true],
            'App\\Controller\\UserController:getUserList' => ['privates', '.service_locator.oGNHoCO', 'get_ServiceLocator_OGNHoCOService', true],
            'App\\Controller\\UserController:linkUser' => ['privates', '.service_locator.sbrKPjh', 'get_ServiceLocator_SbrKPjhService', true],
            'App\\Controller\\UserController:updateUser' => ['privates', '.service_locator.80_A3kY', 'get_ServiceLocator_80A3kYService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\BrandController::createBrand' => '?',
            'App\\Controller\\BrandController::deleteBrand' => '?',
            'App\\Controller\\BrandController::getBrandList' => '?',
            'App\\Controller\\BrandController::getDetailBrand' => '?',
            'App\\Controller\\BrandController::updateBrand' => '?',
            'App\\Controller\\MobileController::createMobile' => '?',
            'App\\Controller\\MobileController::deleteMobile' => '?',
            'App\\Controller\\MobileController::getAllMobiles' => '?',
            'App\\Controller\\MobileController::getDetailMobile' => '?',
            'App\\Controller\\MobileController::updateMobile' => '?',
            'App\\Controller\\UserController::createClient' => '?',
            'App\\Controller\\UserController::createUser' => '?',
            'App\\Controller\\UserController::deleteClient' => '?',
            'App\\Controller\\UserController::deleteUser' => '?',
            'App\\Controller\\UserController::getClientList' => '?',
            'App\\Controller\\UserController::getDetailClient' => '?',
            'App\\Controller\\UserController::getDetailUser' => '?',
            'App\\Controller\\UserController::getUserList' => '?',
            'App\\Controller\\UserController::linkUser' => '?',
            'App\\Controller\\UserController::updateUser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\BrandController:createBrand' => '?',
            'App\\Controller\\BrandController:deleteBrand' => '?',
            'App\\Controller\\BrandController:getBrandList' => '?',
            'App\\Controller\\BrandController:getDetailBrand' => '?',
            'App\\Controller\\BrandController:updateBrand' => '?',
            'App\\Controller\\MobileController:createMobile' => '?',
            'App\\Controller\\MobileController:deleteMobile' => '?',
            'App\\Controller\\MobileController:getAllMobiles' => '?',
            'App\\Controller\\MobileController:getDetailMobile' => '?',
            'App\\Controller\\MobileController:updateMobile' => '?',
            'App\\Controller\\UserController:createClient' => '?',
            'App\\Controller\\UserController:createUser' => '?',
            'App\\Controller\\UserController:deleteClient' => '?',
            'App\\Controller\\UserController:deleteUser' => '?',
            'App\\Controller\\UserController:getClientList' => '?',
            'App\\Controller\\UserController:getDetailClient' => '?',
            'App\\Controller\\UserController:getDetailUser' => '?',
            'App\\Controller\\UserController:getUserList' => '?',
            'App\\Controller\\UserController:linkUser' => '?',
            'App\\Controller\\UserController:updateUser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
