<?php

namespace ContainerG67WXxn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TP9sdH3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tP9sdH3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tP9sdH3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'clientRepository' => ['privates', 'App\\Repository\\ClientRepository', 'getClientRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'serializer' => ['services', 'jms_serializer', 'getJmsSerializerService', true],
            'urlGenerator' => ['services', 'router', 'getRouterService', false],
        ], [
            'clientRepository' => 'App\\Repository\\ClientRepository',
            'em' => '?',
            'serializer' => '?',
            'urlGenerator' => '?',
        ]);
    }
}
