<?php

namespace ContainerG67WXxn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RUHXTmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rU_hXTm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rU_hXTm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cache' => ['privates', 'cache.app.taggable', 'getCache_App_TaggableService', true],
            'clientRepository' => ['privates', 'App\\Repository\\ClientRepository', 'getClientRepositoryService', true],
            'serializer' => ['services', 'jms_serializer', 'getJmsSerializerService', true],
        ], [
            'cache' => '?',
            'clientRepository' => 'App\\Repository\\ClientRepository',
            'serializer' => '?',
        ]);
    }
}
