<?php

namespace ContainerOG0TM0S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVersioningService2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.q.Wxh1..App\Service\VersioningService' shared service.
     *
     * @return \App\Service\VersioningService
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.q.Wxh1.": it references class "App\\Service\\VersioningService" but no such service exists.');
    }
}
