<?php

namespace ContainerPcIEr6M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JzYEaGFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jzYEaGF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jzYEaGF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'brandRepository' => ['privates', 'App\\Repository\\BrandRepository', 'getBrandRepositoryService', true],
            'currentMobile' => ['privates', '.errored..service_locator.jzYEaGF.App\\Entity\\Mobile', NULL, 'Cannot autowire service ".service_locator.jzYEaGF": it needs an instance of "App\\Entity\\Mobile" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', true],
        ], [
            'brandRepository' => 'App\\Repository\\BrandRepository',
            'currentMobile' => 'App\\Entity\\Mobile',
            'em' => '?',
            'serializer' => '?',
        ]);
    }
}
