<?php

namespace ContainerPcIEr6M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WdJquDUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WdJquDU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WdJquDU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'client' => ['privates', '.errored..service_locator.WdJquDU.App\\Entity\\Client', NULL, 'Cannot autowire service ".service_locator.WdJquDU": it needs an instance of "App\\Entity\\Client" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'client' => 'App\\Entity\\Client',
            'em' => '?',
        ]);
    }
}
