<?php

namespace ContainerPcIEr6M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBrandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Y58uPq8.App\Entity\Brand' shared service.
     *
     * @return \App\Entity\Brand
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Y58uPq8": it needs an instance of "App\\Entity\\Brand" but this type has been excluded in "config/services.yaml".');
    }
}
