<?php

namespace ContainerENWX4Yx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7WzCWlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7_wzCWl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7_wzCWl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mobileRepository' => ['privates', 'App\\Repository\\MobileRepository', 'getMobileRepositoryService', true],
            'serializer' => ['services', 'jms_serializer', 'getJmsSerializerService', true],
            'versioningService' => ['privates', 'App\\Service\\VersioningService', 'getVersioningServiceService', true],
        ], [
            'mobileRepository' => 'App\\Repository\\MobileRepository',
            'serializer' => '?',
            'versioningService' => 'App\\Service\\VersioningService',
        ]);
    }
}
