<?php

namespace ContainerENWX4Yx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4s2k69fService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4s2k69f' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4s2k69f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BrandController::createBrand' => ['privates', '.service_locator.U1eLwaY', 'get_ServiceLocator_U1eLwaYService', true],
            'App\\Controller\\BrandController::deleteBrand' => ['privates', '.service_locator.riyQT5B', 'get_ServiceLocator_RiyQT5BService', true],
            'App\\Controller\\BrandController::getBrandList' => ['privates', '.service_locator.h95eEDj', 'get_ServiceLocator_H95eEDjService', true],
            'App\\Controller\\BrandController::getDetailBrand' => ['privates', '.service_locator.Y58uPq8', 'get_ServiceLocator_Y58uPq8Service', true],
            'App\\Controller\\BrandController::updateBrand' => ['privates', '.service_locator.dfP61RH', 'get_ServiceLocator_DfP61RHService', true],
            'App\\Controller\\ClientController::createClient' => ['privates', '.service_locator.tP9sdH3', 'get_ServiceLocator_TP9sdH3Service', true],
            'App\\Controller\\ClientController::deleteClient' => ['privates', '.service_locator.WdJquDU', 'get_ServiceLocator_WdJquDUService', true],
            'App\\Controller\\ClientController::getClientList' => ['privates', '.service_locator.rU_hXTm', 'get_ServiceLocator_RUHXTmService', true],
            'App\\Controller\\ClientController::getDetailClient' => ['privates', '.service_locator.1olE4d7', 'get_ServiceLocator_1olE4d7Service', true],
            'App\\Controller\\ClientController::updateClient' => ['privates', '.service_locator.4CfP.mS', 'get_ServiceLocator_4CfP_MSService', true],
            'App\\Controller\\MobileController::createMobile' => ['privates', '.service_locator.K3s_sj8', 'get_ServiceLocator_K3sSj8Service', true],
            'App\\Controller\\MobileController::deleteMobile' => ['privates', '.service_locator.SZvQUVg', 'get_ServiceLocator_SZvQUVgService', true],
            'App\\Controller\\MobileController::getAllMobiles' => ['privates', '.service_locator.Ekshx4r', 'get_ServiceLocator_Ekshx4rService', true],
            'App\\Controller\\MobileController::getDetailMobile' => ['privates', '.service_locator.q.Wxh1.', 'get_ServiceLocator_Q_Wxh1_Service', true],
            'App\\Controller\\MobileController::getMobileList' => ['privates', '.service_locator.7_wzCWl', 'get_ServiceLocator_7WzCWlService', true],
            'App\\Controller\\MobileController::updateMobile' => ['privates', '.service_locator.l_CQc.y', 'get_ServiceLocator_LCQc_YService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\BrandController:createBrand' => ['privates', '.service_locator.U1eLwaY', 'get_ServiceLocator_U1eLwaYService', true],
            'App\\Controller\\BrandController:deleteBrand' => ['privates', '.service_locator.riyQT5B', 'get_ServiceLocator_RiyQT5BService', true],
            'App\\Controller\\BrandController:getBrandList' => ['privates', '.service_locator.h95eEDj', 'get_ServiceLocator_H95eEDjService', true],
            'App\\Controller\\BrandController:getDetailBrand' => ['privates', '.service_locator.Y58uPq8', 'get_ServiceLocator_Y58uPq8Service', true],
            'App\\Controller\\BrandController:updateBrand' => ['privates', '.service_locator.dfP61RH', 'get_ServiceLocator_DfP61RHService', true],
            'App\\Controller\\ClientController:createClient' => ['privates', '.service_locator.tP9sdH3', 'get_ServiceLocator_TP9sdH3Service', true],
            'App\\Controller\\ClientController:deleteClient' => ['privates', '.service_locator.WdJquDU', 'get_ServiceLocator_WdJquDUService', true],
            'App\\Controller\\ClientController:getClientList' => ['privates', '.service_locator.rU_hXTm', 'get_ServiceLocator_RUHXTmService', true],
            'App\\Controller\\ClientController:getDetailClient' => ['privates', '.service_locator.1olE4d7', 'get_ServiceLocator_1olE4d7Service', true],
            'App\\Controller\\ClientController:updateClient' => ['privates', '.service_locator.4CfP.mS', 'get_ServiceLocator_4CfP_MSService', true],
            'App\\Controller\\MobileController:createMobile' => ['privates', '.service_locator.K3s_sj8', 'get_ServiceLocator_K3sSj8Service', true],
            'App\\Controller\\MobileController:deleteMobile' => ['privates', '.service_locator.SZvQUVg', 'get_ServiceLocator_SZvQUVgService', true],
            'App\\Controller\\MobileController:getAllMobiles' => ['privates', '.service_locator.Ekshx4r', 'get_ServiceLocator_Ekshx4rService', true],
            'App\\Controller\\MobileController:getDetailMobile' => ['privates', '.service_locator.q.Wxh1.', 'get_ServiceLocator_Q_Wxh1_Service', true],
            'App\\Controller\\MobileController:getMobileList' => ['privates', '.service_locator.7_wzCWl', 'get_ServiceLocator_7WzCWlService', true],
            'App\\Controller\\MobileController:updateMobile' => ['privates', '.service_locator.l_CQc.y', 'get_ServiceLocator_LCQc_YService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\BrandController::createBrand' => '?',
            'App\\Controller\\BrandController::deleteBrand' => '?',
            'App\\Controller\\BrandController::getBrandList' => '?',
            'App\\Controller\\BrandController::getDetailBrand' => '?',
            'App\\Controller\\BrandController::updateBrand' => '?',
            'App\\Controller\\ClientController::createClient' => '?',
            'App\\Controller\\ClientController::deleteClient' => '?',
            'App\\Controller\\ClientController::getClientList' => '?',
            'App\\Controller\\ClientController::getDetailClient' => '?',
            'App\\Controller\\ClientController::updateClient' => '?',
            'App\\Controller\\MobileController::createMobile' => '?',
            'App\\Controller\\MobileController::deleteMobile' => '?',
            'App\\Controller\\MobileController::getAllMobiles' => '?',
            'App\\Controller\\MobileController::getDetailMobile' => '?',
            'App\\Controller\\MobileController::getMobileList' => '?',
            'App\\Controller\\MobileController::updateMobile' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\BrandController:createBrand' => '?',
            'App\\Controller\\BrandController:deleteBrand' => '?',
            'App\\Controller\\BrandController:getBrandList' => '?',
            'App\\Controller\\BrandController:getDetailBrand' => '?',
            'App\\Controller\\BrandController:updateBrand' => '?',
            'App\\Controller\\ClientController:createClient' => '?',
            'App\\Controller\\ClientController:deleteClient' => '?',
            'App\\Controller\\ClientController:getClientList' => '?',
            'App\\Controller\\ClientController:getDetailClient' => '?',
            'App\\Controller\\ClientController:updateClient' => '?',
            'App\\Controller\\MobileController:createMobile' => '?',
            'App\\Controller\\MobileController:deleteMobile' => '?',
            'App\\Controller\\MobileController:getAllMobiles' => '?',
            'App\\Controller\\MobileController:getDetailMobile' => '?',
            'App\\Controller\\MobileController:getMobileList' => '?',
            'App\\Controller\\MobileController:updateMobile' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
