<?php

namespace Container6LZ6dTG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_L9fkoJCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.L9fkoJC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.L9fkoJC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\MobileController::getDetailMobile' => ['privates', '.service_locator.nfaZhBu', 'get_ServiceLocator_NfaZhBuService', true],
            'App\\Controller\\MobileController::getMobileList' => ['privates', '.service_locator.tRDWS_A', 'get_ServiceLocator_TRDWSAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\MobileController:getDetailMobile' => ['privates', '.service_locator.nfaZhBu', 'get_ServiceLocator_NfaZhBuService', true],
            'App\\Controller\\MobileController:getMobileList' => ['privates', '.service_locator.tRDWS_A', 'get_ServiceLocator_TRDWSAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\MobileController::getDetailMobile' => '?',
            'App\\Controller\\MobileController::getMobileList' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\MobileController:getDetailMobile' => '?',
            'App\\Controller\\MobileController:getMobileList' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
