<?php

namespace ContainerMOMBdsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1olE4d7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1olE4d7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1olE4d7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'client' => ['privates', '.errored..service_locator.1olE4d7.App\\Entity\\Client', NULL, 'Cannot autowire service ".service_locator.1olE4d7": it needs an instance of "App\\Entity\\Client" but this type has been excluded in "config/services.yaml".'],
            'serializer' => ['services', 'jms_serializer', 'getJmsSerializerService', true],
        ], [
            'client' => 'App\\Entity\\Client',
            'serializer' => '?',
        ]);
    }
}
