<?php

namespace ContainerMOMBdsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JhoR5yOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jhoR5yO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jhoR5yO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'currentUser' => ['privates', '.errored..service_locator.jhoR5yO.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.jhoR5yO": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'serializer' => ['services', 'jms_serializer', 'getJmsSerializerService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'currentUser' => 'App\\Entity\\User',
            'em' => '?',
            'serializer' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
