<?php

namespace ContainerMOMBdsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GkGK2OSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GkGK2OS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GkGK2OS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'user' => ['privates', '.errored..service_locator.GkGK2OS.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.GkGK2OS": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
