<?php

namespace Container9WwKTxh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMobile2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.l_CQc.y.App\Entity\Mobile' shared service.
     *
     * @return \App\Entity\Mobile
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.l_CQc.y": it needs an instance of "App\\Entity\\Mobile" but this type has been excluded in "config/services.yaml".');
    }
}
