<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9WwKTxh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9WwKTxh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9WwKTxh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9WwKTxh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9WwKTxh\App_KernelDevDebugContainer([
    'container.build_hash' => '9WwKTxh',
    'container.build_id' => 'd6d97419',
    'container.build_time' => 1681396268,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9WwKTxh');
